### ISSUE TITLE
Handle :optimization :none

### ISSUE THREAD

**Issue by mike-thompson-day8** [slagyr/speclj#100]
Currently specljs doesn't handle the cljsbuild option`:optimizations :none`. 

You might be interested to see how I got it to work for `com.cemerick/clojurescript.test` because the principal would transfer fairly easily to specljs.

See this [seed project] - which contains a link to a gist for specljs.

BTW, as feedback:  although we liked specljs, we can't use it because it doesn't handle async tests, which is a show stopper for us.  We will have to go back to cemeric/clojurescript.test for the moment.

[seed project]:https://github.com/mike-thompson-day8/cljsbuild-none-test-seed

**Comment by slagyr** [comment]
#118 addresses the async aspect.

As for :optimizations :none, it requires a new means of running the specs.  The way I've done it is by creating a web page that'll run the specs, and invoking them with phantom.  Auto running can be achieved this way too.  

This is better addressed by the speclj-template project: https://github.com/ecmendenhall/specljs-template

Issue moved: https://github.com/ecmendenhall/specljs-template/issues/2
