### ISSUE TITLE
Vigilant runner and standard runner sometimes run a differing number of tests

### ISSUE THREAD

**Issue by sdegutis** [slagyr/speclj#113]
When running `lein spec` it runs 499 examples. When running `lein spec -a` it runs 494 examples.

**Comment by slagyr** [comment]
After a quick perusal of the code, I don't see why this might happen.  It would be helpful to know what is causing this in your code base.  Do you have an example?  Maybe there's something funky like a filename with - instead of a _.

**Comment by sdegutis** [comment]
@slagyr Just found the problematic tests. It's only happening for test files inside a directory called `test_helpers` where each file's `ns` Clojure form has `test-helpers` inside the namespace path. But the directory correctly has an underscore and the namespace path correctly has a dash, so that shouldn't be the problem. It seems like the vigilant runner is not seeing the files inside `test_helpers` for some reason. I'll investigate further.
