### ISSUE TITLE
Code in around not executing on spec failures

### ISSUE THREAD

**Issue by dcmoore** [slagyr/speclj#117]
Any code after the characteristic doesn't execute if the characteristic fails. This can make test cleanup hard, and sometimes cause test pollution.

```clojure
(around [it]
  (let [original-value @stateful-var]
    (it)
    (reset! stateful-var original-value)))
```

**Comment by slagyr** [comment]
After much discussion with @trptcolin and experimentation, we concluded that the best option is to do nothing.  Will not Fix.

If you have cleanup to do, add a try/finally block to your around code:

```clojure
(around [it]
  (let [original-value @stateful-var]
    (try
      (it)
      (finally
         (reset! stateful-var original-value)))))
```

A doc comment to this effect has been added to the source.
