### ISSUE TITLE
Ability to terminate test executions at first error

### ISSUE THREAD

**Issue by hlship** [slagyr/speclj#120]
My tests tend to generate a LOT of output while running, it somewhat unavoidable ... mostly because I need that output to figure out what's gone on when there's a failure.

What I would really like is an option to terminate the test execution early if there is a test failure. This would significantly improve my signal-to-noise ratio.

Currently using Speclj 3.1.0.

**Comment by slagyr** [comment]
Closing as duplicate of https://github.com/slagyr/speclj/issues/105
