### ISSUE TITLE
Allow -a and --format=p options together

### ISSUE THREAD

**Issue by eigenhombre** [slagyr/speclj#130]
Currently `--format=p` only works if `-a` is omitted.  Sure'd be nice to be able to do both at once.  Cheers!

**Comment by sdegutis** [comment]
@eigenhombre The `-a` flag is only a synonym for `--reporter=documentation --runner=vigilant` and `--format` is just an alias for `--reporter`, so you can accomplish what you're trying to do with `--format=progress --runner=vigilant` or `--format=progress -r v` for short. Does that work for you?

**Comment by eigenhombre** [comment]
@sdegutis Yes, thanks a lot!

**Comment by sdegutis** [comment]
Great, glad to hear it.

**Comment by eigenhombre** [comment]
I will say that this would be a good addition to the docs, particularly for people coming to Clojure from Python (and who are used to `nose`).  Cheers!
