### ISSUE TITLE
Support for `*.cljc` files in vigilant mode?

### ISSUE THREAD

**Issue by Jell** [slagyr/speclj#131]
`*.cljc` files are not being watched or reloaded when working with both Clojure and ClojureScript.

With the release of clojure 1.7 around the corner, it would be nice to support those as they will be part of the core language.

I've opened a corresponding request to the underlying "fresh" library here: https://github.com/slagyr/fresh/issues/2

**Comment by slagyr** [comment]
Yeah... that's annoying, huh?  At least it was for me.  Version 3.3.0 (soon to be released) fixes this.

**Comment by Jell** [comment]
Thanks a bunch! :)

**Comment by milt** [comment]
Still seeing this with 3.3.0, but perhaps I am doing something wrong. When I try running `lein spec -a` with a core_spec.cljc like this:
```clojure
(ns my-project.core-spec
  #?(:cljs
     (:require-macros
      [speclj.core :refer [describe it should run-specs]]))
  (:require
   #?@(:cljs [[speclj.core]]
       :clj [[speclj.core :refer :all]])))

(describe "foo"
          (it "does stuff"
              (should true)))

(run-specs)
```

It will give me this:

```
----- Mon Jun 22 12:44:35 EDT 2015 -------------------------------------------------------------------
took 0.12333 to determine file statuses.
reloading files:
  /Users/milt/projects/my-project/spec/my_project/core_spec.cljc
```

...but not run the tests. `lein spec` works as expected. Changes to the file will get it to reload, but the test still doesn't run.

**Comment by slagyr** [comment]
A little bit of researching revealed that reader conditionals must be enabled when you call clojure.core/read. Speclj has been updated to do this.  Checkout 3.3.1.

**Comment by milt** [comment]
Oh wow, that helps me elsewhere too. You are awesome!
