### ISSUE TITLE
'Expected' vs 'got'

### ISSUE THREAD

**Issue by beccanelson** [slagyr/speclj#156]
It's always been my understanding that in the spec results, `Expected:` refers to the expected result of the test case, and `got:` refers to the actual return value when running the program. Whenever I run my tests, these values seem to be reversed. Is there a reason for this?

**Comment by eyelidlessness** [comment]
It appears to be based on the order specified: `(should= :expected :actual)`. The [docstring](https://github.com/slagyr/speclj/blob/master/src/speclj/core.cljc#L205-L207) confirms this. I imagine it would be quite difficult to determine which value is the result of some program code.

**Comment by beccanelson** [comment]
Oh, okay. I guess my arguments are just in the wrong order!  Nevermind! 😑
