### ISSUE TITLE
got this error: TypeError: 'undefined' is not an object (evaluating 'cljs.core.require.call')

### ISSUE THREAD

**Issue by pbaille** [slagyr/speclj#89]
it point to this line of my main.js
cljs.core.require.call(null, new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null, "speclj.cli", "speclj.cli", 1748828644, null)], null));

any idea? I don't understand at all

**Comment by slagyr** [comment]
I see.  run-specs is a macro that's not expected in cljs specs.  I've updated the macro to be benign when compiling cljs specs.
